.\"
.\" Copyright (c) 2003-2007 Silicon Graphics, Inc.
.\" All Rights Reserved.
.\"
.TH job_waitjid 3
.SH NAME
job_waitjid \- wait for a job to complete
.SH SYNOPSIS
.nf
\f3#include <job.h>\f1
.sp .8v
\f3jid_t job_waitjid( jid_t jid, int *status, int options );\f1
.fi
.SH DESCRIPTION
The \f4job_waitjid\f1 library call is part of the job library that allows
processes to manipulate and obtain status about linux jobs.
When the job library is to be used, the
\f3job.h\f1 header file should be included to obtain the proper definitions.
.PP
\f4job_waitjid\f1 
will wait until the specified job completes,
or until a signal is delivered whose action is to terminate
the current process or to call a signal handling function.
It returns the status information for the last process to exit the job.
.PP
.SH DIAGNOSTICS
Upon successful completion, \f2job_waitjid\f1 returns
the job ID of the job waited for.
Otherwise, a value of (jid_t)-1 is returned and \f3errno\f1 is set to
indicate the error.  Note that you need to test for -1 using a cast.  
See the job_create(3) man page for an example.
.SH SEE ALSO
job_create(3), job_detachjid(3), job_detachpid(3), job_attachpid(3), job_getjid(3), job_getjidcnt(3), job_getjidlist(3), job_getpidcnt(3), job_getpidlist(3), job_getprimepid(3), job_getuid(3), job_killjid(3), job_sethid(3),  job(7).

