.\"
.\" Copyright (c) 2003-2007 Silicon Graphics, Inc.  
.\" All Rights Reserved.
.\"
.TH job_detachjid 3
.SH NAME
job_detachjid \- detach all the processes from a job
.SH SYNOPSIS
.nf
\f3#include <job.h>\f1
.sp .8v
\f3int job_detachjid( jid_t jid );\f1
.fi
.SH DESCRIPTION
The \f4job_detachjid\f1 library call is part of the job library that allows
processes to manipulate and obtain status about linux jobs.
When the job library is to be used, the
\f3job.h\f1 header file should be included to obtain the proper definitions.
.PP
\f4job_detachjid\f1 
will detach all the processes from a job,
but allows the processes to continue running.
You need CAP_SYS_RESOURCE capability for this to succeed.
Since all processes will be detached, the job will exit.

.PP
.SH DIAGNOSTICS
Upon successful completion, \f2job_detachjid\f1 returns
a count of the number of processes detached from the job.
Otherwise, a value of -1 is returned and \f3errno\f1 is set to
indicate the error.
.SH SEE ALSO
job_create(3), job_detachpid(3), job_attachpid(3), job_getjid(3), job_getjidcnt(3), job_getjidlist(3), job_getpidcnt(3), job_getpidlist(3), job_getprimepid(3), job_getuid(3), job_killjid(3), job_sethid(3), job_waitjid(3),  job(7).

